import {readFileSync,writeFileSync,unlinkSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';

const run=(cmd,args=[],options={})=>execFileSync(cmd,args,{stdio:'inherit',...options});
const appPath='app/src/main/assets/app.js';
const cssPath='app/src/main/assets/styles.css';
const gradlePath='app/build.gradle';
const activityPath='app/src/main/java/tv/swoop/player/MainActivity.java';
const testPath='tests/tv-ui-runtime-smoke.mjs';
const notesPath='RELEASE_NOTES.md';
const selfPath='.promotion/promote-pending.mjs';

function replaceRequired(source,search,replacement,label){
  const next=source.replace(search,replacement);
  if(next===source)throw new Error(`v0.8.38 promotion could not patch ${label}`);
  return next;
}

let app=readFileSync(appPath,'utf8');
app=replaceRequired(app,"const ANDROID_CURRENT_VERSION='0.8.37';","const ANDROID_CURRENT_VERSION='0.8.38';",'Android current version');
app=replaceRequired(app,"const STARMETER_INITIAL_VISIBLE=100,STARMETER_APPEND_BATCH=100,STARMETER_HYDRATE_CONCURRENCY=2,STARMETER_PREFETCH_AHEAD=6,STARMETER_TITLE_RENDER_LIMIT=8;","const STARMETER_INITIAL_VISIBLE=100,STARMETER_APPEND_BATCH=100,STARMETER_HYDRATE_CONCURRENCY=2,STARMETER_PREFETCH_AHEAD=6,STARMETER_TITLE_RENDER_LIMIT=8,STARMETER_PATCH_BATCH=3,STARMETER_ACTIVE_RADIUS=7,STARMETER_ART_RADIUS=8;",'STARmeter runtime constants');
app=replaceRequired(app,"  'Fixes the physical-TV STARmeter renderer crash by sharply reducing resident artwork memory and title-card pressure while preserving stable person rows.',","  'Stops STARmeter blank/repaint stalls during held-D-pad traversal by batching deferred row patches, unloading distant artwork and serving TV-sized STARmeter images.',",'v0.8.38 changelog lead item');
app=replaceRequired(app,/function optimizedArtworkUrl\(url,img\)\{[\s\S]*?\}\nfunction revealArtwork/,`function optimizedArtworkUrl(url,img){const raw=String(url||'');if(!/image\\.tmdb\\.org\\/t\\/p\\//i.test(raw))return raw;const cls=img?.className||'';let size='w500';if(img?.closest?.('.starmeter-title-rail'))size='w154';else if(img?.closest?.('.starmeter-person-card'))size='w185';else if(/backdrop|hero-art|hero-backdrop|detail-backdrop/i.test(cls))size='w1280';else if(/title-logo/i.test(cls))size='w500';else if(/cast/i.test(cls))size='w185';else if(img?.closest?.('.poster, .poster-content-grid'))size='w342';return raw.replace(/\\/t\\/p\\/(?:original|w\\d+)\\//i,\`/t/p/\${size}/\`)}\nfunction revealArtwork`,'STARmeter artwork sizing');
app=replaceRequired(app,/function hydrateArtwork\(root=document\)\{[\s\S]*?\}\n\nlet searchIndexKey=/,`function hydrateArtwork(root=document){const imgs=[...root.querySelectorAll('img[data-swoop-art]')].filter(img=>img.dataset.swoopLoaded!=='1');if(!imgs.length)return;const starmeterTv=NATIVE_ANDROID&&state.page==='starmeter';const immediate=imgs.filter(img=>/title-logo|hero|detail-backdrop/i.test(img.className||'')||artworkNearViewport(img,starmeterTv?720:600,starmeterTv?900:1300));immediate.forEach(img=>loadArtwork(img,{priority:'high'}));const deferred=imgs.filter(img=>!immediate.includes(img));if(!deferred.length||starmeterTv)return;if(!('IntersectionObserver'in window)){deferred.forEach(img=>loadArtwork(img,{priority:'normal'}));return}if(!artworkObserver)artworkObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){artworkObserver?.unobserve(entry.target);loadArtwork(entry.target,{priority:'high'})}},{rootMargin:largeLibraryMode()?'700px 1200px':'1000px 1800px',threshold:.01});deferred.forEach(img=>artworkObserver.observe(img))}\n\nlet searchIndexKey=`,'STARmeter lazy artwork hydration');
const oldMutation="function starmeterMutationBlocked(){return starmeterHeldDirectional||starmeterHeldKeys.size>0||performance.now()-starmeterLastFocusMoveAt<240}";
const newMutation=`function starmeterMutationBlocked(){return starmeterHeldDirectional||starmeterHeldKeys.size>0||performance.now()-starmeterLastFocusMoveAt<240}\nlet starmeterArtworkTrimTimer=null;\nfunction starmeterActiveRank(){const focused=Number(document.activeElement?.closest?.('[data-starmeter-rank]')?.dataset?.starmeterRank||0);if(focused)return focused;let best=0,bestDistance=Infinity;const mid=Math.max(1,innerHeight||1080)/2;for(const section of document.querySelectorAll('.starmeter-person-section')){const r=section.getBoundingClientRect(),distance=Math.abs(((r.top+r.bottom)/2)-mid);if(distance<bestDistance){bestDistance=distance;best=Number(section.dataset.starmeterRank||0)}}return best}\nfunction starmeterSectionNearViewport(section,pad=620){if(!section)return false;const r=section.getBoundingClientRect(),h=Math.max(1,innerHeight||1080);return r.bottom>=-pad&&r.top<=h+pad}\nfunction starmeterPatchEligible(rank){const value=Number(rank||0),section=value?document.querySelector(\`[data-starmeter-rank="\${value}"]\`):null,active=starmeterActiveRank();return !!section&&((active&&Math.abs(value-active)<=STARMETER_ACTIVE_RADIUS)||starmeterSectionNearViewport(section,620))}\nfunction trimStarmeterArtwork(){starmeterArtworkTrimTimer=null;if(state.page!=='starmeter')return;const active=starmeterActiveRank(),h=Math.max(1,innerHeight||1080);for(const section of document.querySelectorAll('.starmeter-person-section')){const rank=Number(section.dataset.starmeterRank||0),r=section.getBoundingClientRect(),near=(active&&Math.abs(rank-active)<=STARMETER_ART_RADIUS)||(r.bottom>=-520&&r.top<=h+520);if(near){hydrateArtwork(section);continue}for(const img of section.querySelectorAll('img[data-swoop-art][src]')){artworkObserver?.unobserve?.(img);img.onload=null;img.onerror=null;img.removeAttribute('src');delete img.dataset.swoopLoaded;img.classList.remove('loaded','artwork-failed');img.closest?.('.card')?.classList.remove('art-ready')}}}\nfunction scheduleStarmeterArtworkTrim(delay=140){if(state.page!=='starmeter'||starmeterArtworkTrimTimer)return;starmeterArtworkTrimTimer=setTimeout(trimStarmeterArtwork,Math.max(60,Number(delay||140)))}`;
app=replaceRequired(app,oldMutation,newMutation,'STARmeter viewport artwork guard');
app=replaceRequired(app,"function cancelStarmeterWork(){starmeterGeneration++;starmeterHydrateQueue.length=0;starmeterHydrateBusy=0;starmeterObserver?.disconnect?.();starmeterObserver=null;starmeterAutoLoadObserver?.disconnect?.();starmeterAutoLoadObserver=null;clearTimeout(starmeterPatchTimer);starmeterPatchTimer=null;starmeterDeferredPatches.clear();starmeterDeferredIdentityPatches.clear();starmeterHeldKeys.clear();starmeterHeldDirectional=false;}","function cancelStarmeterWork(){starmeterGeneration++;starmeterHydrateQueue.length=0;starmeterHydrateBusy=0;starmeterObserver?.disconnect?.();starmeterObserver=null;starmeterAutoLoadObserver?.disconnect?.();starmeterAutoLoadObserver=null;clearTimeout(starmeterPatchTimer);starmeterPatchTimer=null;clearTimeout(starmeterArtworkTrimTimer);starmeterArtworkTrimTimer=null;starmeterDeferredPatches.clear();starmeterDeferredIdentityPatches.clear();starmeterHeldKeys.clear();starmeterHeldDirectional=false;}",'STARmeter cancellation cleanup');
app=replaceRequired(app,"if(state.page!=='starmeter'||starmeterSectionIsActive(section)||starmeterMutationBlocked()){starmeterDeferredIdentityPatches.set(value,person);scheduleStarmeterPatchFlush();return false}return patchStarmeterIdentityNow(value,person);","if(state.page!=='starmeter'||starmeterSectionIsActive(section)||starmeterMutationBlocked()||!starmeterPatchEligible(value)){starmeterDeferredIdentityPatches.set(value,person);scheduleStarmeterPatchFlush();return false}return patchStarmeterIdentityNow(value,person);",'offscreen STARmeter identity deferral');
app=replaceRequired(app,/function flushStarmeterDeferredPatches\(\)\{[\s\S]*?\}\nfunction patchStarmeterPerson\(rank\)/,`function flushStarmeterDeferredPatches(){\n  clearTimeout(starmeterPatchTimer);starmeterPatchTimer=null;if(state.page!=='starmeter'||detailItem||personView){starmeterDeferredPatches.clear();starmeterDeferredIdentityPatches.clear();return}\n  if(starmeterMutationBlocked()){scheduleStarmeterPatchFlush(180);scheduleStarmeterArtworkTrim(120);return}\n  const activeRank=starmeterActiveRank(),distance=rank=>activeRank?Math.abs(Number(rank||0)-activeRank):0;let budget=STARMETER_PATCH_BATCH;\n  const identity=[...starmeterDeferredIdentityPatches].filter(([rank])=>starmeterPatchEligible(rank)).sort((a,b)=>distance(a[0])-distance(b[0]));\n  for(const [rank,person] of identity){if(budget<=0)break;if(Number(rank)===activeRank)continue;if(patchStarmeterIdentityNow(rank,person)){starmeterDeferredIdentityPatches.delete(rank);budget--}}\n  const rows=[...starmeterDeferredPatches].filter(rank=>starmeterPatchEligible(rank)).sort((a,b)=>distance(a)-distance(b));\n  for(const rank of rows){if(budget<=0)break;if(Number(rank)===activeRank)continue;if(patchStarmeterPersonNow(rank)){starmeterDeferredPatches.delete(rank);budget--}}\n  scheduleStarmeterArtworkTrim(90);\n  const moreEligible=[...starmeterDeferredIdentityPatches.keys()].some(starmeterPatchEligible)||[...starmeterDeferredPatches].some(starmeterPatchEligible);if(moreEligible)scheduleStarmeterPatchFlush(110)\n}\nfunction patchStarmeterPerson(rank)`,'bounded STARmeter deferred patch flush');
app=replaceRequired(app,"if(section&&card){const index=cards.indexOf(card);if(index>=0)tvRowColumnMemory.set(tvRailSectionKey(section),index);tvPrefetchArtworkWindow(card,state.page==='home'?32:24,4);longRailPrefetchForFocus(card)}","if(section&&card){const index=cards.indexOf(card);if(index>=0)tvRowColumnMemory.set(tvRailSectionKey(section),index);if(state.page!=='starmeter'){tvPrefetchArtworkWindow(card,state.page==='home'?32:24,4);longRailPrefetchForFocus(card)}}",'STARmeter generic artwork prefetch bypass');
app=replaceRequired(app,"if(state.page==='starmeter'){starmeterLastFocusMoveAt=performance.now();const personSection=el.closest?.('[data-starmeter-rank]'),rank=Number(personSection?.dataset?.starmeterRank||0),idx=rank?starmeterPeople.findIndex(x=>Number(x.rank)===rank):-1;if(idx>=0){queueStarmeterPerson(starmeterPeople[idx],{priority:true});for(let ahead=1;ahead<=STARMETER_PREFETCH_AHEAD;ahead++){const next=starmeterPeople[idx+ahead];if(next)queueStarmeterPerson(next,{priority:ahead<=6})}}if(starmeterDeferredPatches.size||starmeterDeferredIdentityPatches.size)scheduleStarmeterPatchFlush(220)}","if(state.page==='starmeter'){starmeterLastFocusMoveAt=performance.now();const personSection=el.closest?.('[data-starmeter-rank]'),rank=Number(personSection?.dataset?.starmeterRank||0),idx=rank?starmeterPeople.findIndex(x=>Number(x.rank)===rank):-1;if(personSection)hydrateArtwork(personSection);scheduleStarmeterArtworkTrim(90);if(idx>=0){queueStarmeterPerson(starmeterPeople[idx],{priority:true});for(let ahead=1;ahead<=STARMETER_PREFETCH_AHEAD;ahead++){const next=starmeterPeople[idx+ahead];if(next)queueStarmeterPerson(next,{priority:ahead<=6})}}if(starmeterDeferredPatches.size||starmeterDeferredIdentityPatches.size)scheduleStarmeterPatchFlush(220)}",'STARmeter focus artwork window');
app=replaceRequired(app,"if(state.page==='starmeter'){starmeterHeldKeys.add(e.key);starmeterLastFocusMoveAt=performance.now();if(e.repeat){starmeterHeldDirectional=true;if(starmeterPatchTimer){clearTimeout(starmeterPatchTimer);starmeterPatchTimer=null}}}","if(state.page==='starmeter'){starmeterHeldKeys.add(e.key);starmeterLastFocusMoveAt=performance.now();if(e.repeat){starmeterHeldDirectional=true;if(starmeterPatchTimer){clearTimeout(starmeterPatchTimer);starmeterPatchTimer=null}scheduleStarmeterArtworkTrim(80)}}",'held-D-pad STARmeter trim');
app=replaceRequired(app,"starmeterHeldKeys.delete(e.key);if(state.page==='starmeter'&&!starmeterHeldKeys.size){starmeterHeldDirectional=false;starmeterLastFocusMoveAt=performance.now();if(starmeterDeferredPatches.size||starmeterDeferredIdentityPatches.size)scheduleStarmeterPatchFlush(280)}","starmeterHeldKeys.delete(e.key);if(state.page==='starmeter'&&!starmeterHeldKeys.size){starmeterHeldDirectional=false;starmeterLastFocusMoveAt=performance.now();scheduleStarmeterArtworkTrim(90);if(starmeterDeferredPatches.size||starmeterDeferredIdentityPatches.size)scheduleStarmeterPatchFlush(300)}",'STARmeter key-release settle');
writeFileSync(appPath,app);

let css=readFileSync(cssPath,'utf8');
if(!css.includes('v0.8.38 — STARmeter viewport-budget hotfix'))css+=`\n\n/* v0.8.38 — STARmeter viewport-budget hotfix. */\nhtml.android-tv .starmeter-person-section{will-change:auto!important;backface-visibility:visible!important}\nhtml.android-tv .starmeter-library-column{will-change:auto!important}\nhtml.android-tv .starmeter-title-rail{grid-auto-flow:column!important;grid-template-rows:100px!important;grid-auto-rows:100px!important;overflow-x:auto!important;overflow-y:hidden!important}\nhtml.android-tv .starmeter-title-rail>.card{contain:layout paint!important}\n`;
writeFileSync(cssPath,css);

let gradle=readFileSync(gradlePath,'utf8');
gradle=replaceRequired(gradle,/versionCode\s+837\b/,'versionCode 838','versionCode');
gradle=replaceRequired(gradle,/versionName\s+['\"]0\.8\.37['\"]/,"versionName '0.8.38'",'versionName');
writeFileSync(gradlePath,gradle);

let activity=readFileSync(activityPath,'utf8');
activity=replaceRequired(activity,/SwoopTV\/0\.8\.37 AndroidTV/g,'SwoopTV/0.8.38 AndroidTV','native Android user agent');
writeFileSync(activityPath,activity);

let tests=readFileSync(testPath,'utf8');
const testMarker='// v0.8.38 STARmeter viewport-budget regression guards';
if(!tests.includes(testMarker))tests+=`\n\n${testMarker}\nif (!appSource.includes("STARMETER_PATCH_BATCH=3,STARMETER_ACTIVE_RADIUS=7,STARMETER_ART_RADIUS=8")) throw new Error('v0.8.38 STARmeter patch/artwork budgets missing');\nif (!appSource.includes("img?.closest?.('.starmeter-title-rail'))size='w154'")) throw new Error('v0.8.38 STARmeter title artwork must request w154');\nif (!appSource.includes("img?.closest?.('.starmeter-person-card'))size='w185'")) throw new Error('v0.8.38 STARmeter portrait artwork must request w185');\nif (!appSource.includes("const starmeterTv=NATIVE_ANDROID&&state.page==='starmeter'")) throw new Error('v0.8.38 STARmeter artwork hydration isolation missing');\nif (!appSource.includes('function trimStarmeterArtwork()')) throw new Error('v0.8.38 offscreen STARmeter artwork eviction missing');\nif (!appSource.includes('let budget=STARMETER_PATCH_BATCH')) throw new Error('v0.8.38 bounded STARmeter deferred patch flush missing');\nif (!cssSource.includes('v0.8.38 — STARmeter viewport-budget hotfix')) throw new Error('v0.8.38 STARmeter CSS guard missing');\nif (!cssSource.includes('grid-auto-flow:column!important;grid-template-rows:100px!important;grid-auto-rows:100px!important')) throw new Error('v0.8.38 STARmeter rail must stay single-row');\nif (!activitySource.includes('SwoopTV/0.8.38 AndroidTV')) throw new Error('v0.8.38 native Android marker missing');\n`;
writeFileSync(testPath,tests);

let notes=readFileSync(notesPath,'utf8');
const section=`## v0.8.38 — STARmeter Viewport-Budget Hotfix\n\n- Fixes the remaining physical Google TV STARmeter blank/repaint stalls visible in IMG_1143.mp4 during sustained vertical D-pad traversal.\n- Keeps the stable 100-person focus geometry, but limits completed async DOM patching to three nearby rows per flush instead of mutating every deferred row after navigation settles.\n- Stops the generic artwork observer/prefetch path from accumulating STARmeter images far outside the current viewport.\n- Actively releases poster/portrait image sources outside an eight-rank working window and reloads them only when those rows return near the viewport.\n- Requests w154 title posters and w185 person portraits for STARmeter instead of much larger generic artwork sizes.\n- Hard-locks the compact STARmeter title rail to one 100 px grid row with vertical overflow clipped.\n\n`;
if(!notes.includes('## v0.8.38 — STARmeter Viewport-Budget Hotfix')){const header='# Swoop TV Release Notes\n\n';notes=notes.startsWith(header)?header+section+notes.slice(header.length):section+notes;writeFileSync(notesPath,notes)}

if(existsSync(selfPath))unlinkSync(selfPath);

for(const p of [appPath,testPath])run(process.execPath,['--check',p]);
run(process.execPath,['tests/card-runtime-smoke.mjs']);
run(process.execPath,[testPath]);
run('python',['-m','json.tool','app/src/main/assets/starmeter.json'],{stdio:'ignore'});

run('git',['config','user.name','github-actions[bot]']);
run('git',['config','user.email','41898282+github-actions[bot]@users.noreply.github.com']);
run('git',['add','-A']);
const status=execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim();
if(!status)throw new Error('v0.8.38 promotion produced no source changes');
run('git',['commit','-m','Promote v0.8.38 STARmeter viewport budget hotfix']);
run('git',['push','origin','HEAD:main']);
console.log('v0.8.38 source promotion complete; continuing APK build and Downloader publication.');
