import fs from 'node:fs';
import {execFileSync} from 'node:child_process';

const path='scripts/refresh-seed-cache.mjs';
let s=fs.readFileSync(path,'utf8');
const anchor=`async function fetchPublicTraktTrending(url,mediaType){\n`;
if(!s.includes(anchor)) throw new Error('Trakt fallback function anchor not found');
const insert=`function parseTraktTrendingSurface(html,mediaType='movie'){\n  const out=[],seen=new Set(),kind=mediaType==='tv'?'shows':'movies';\n  const source=String(html||'');\n  const anchorPattern=new RegExp('<a\\\\b[^>]*href=["\\\\'](?:https?:\\\\/\\\\/(?:www\\\\.)?trakt\\\\.tv)?\\\\/'+kind+'\\\\/[^"\\\\']+["\\\\'][^>]*>([\\\\s\\\\S]*?)<\\\\/a>','gi');\n  let match;\n  while((match=anchorPattern.exec(source))){\n    const text=decodeHtmlText(String(match[1]||'').replace(/<[^>]+>/g,' ')).replace(/\\s+/g,' ').trim();\n    const m=text.match(/^(.{1,180}?)\\s+((?:19|20)\\d{2})$/);\n    if(!m)continue;\n    const title=m[1].trim(),year=m[2],key=\`${'${normalize(title)}'}|\${year}\`;\n    if(!normalize(title)||seen.has(key))continue;\n    seen.add(key);out.push({title,year,media_type:mediaType,ids:{}});\n  }\n  return out;\n}\nasync function fetchTraktMediaSurface(mediaType){\n  const items=[],seen=new Set(),kind=mediaType==='tv'?'shows':'movies';\n  for(let page=1;page<=5&&items.length<120;page++){\n    const url=\`https://media-og.trakt.tv/\${kind}/trending\${page>1?'?page='+page:''}\`;\n    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);\n    try{\n      const res=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/142 Safari/537.36','accept':'text/html,application/xhtml+xml'},signal:controller.signal,redirect:'follow'});\n      if(!res.ok)throw new Error(\`Trakt media surface page \${page} HTTP \${res.status}\`);\n      const rows=parseTraktTrendingSurface(await res.text(),mediaType);\n      let added=0;\n      for(const row of rows){const key=\`\${normalize(row.title)}|\${row.year}\`;if(seen.has(key))continue;seen.add(key);items.push(row);added++;}\n      console.log(\`Trakt media surface \${kind} page \${page}: \${rows.length} parsed, \${added} new, \${items.length} total.\`);\n      if(!rows.length||!added)break;\n    }finally{clearTimeout(timer)}\n  }\n  if(items.length<100)throw new Error(\`Trakt media surface found only \${items.length} \${mediaType} entries\`);\n  return {items:items.slice(0,100),source:'Trakt Trending · current public media surface',sourceUrl:\`https://media-og.trakt.tv/\${kind}/trending\`,sourceUpdatedAt:Date.now()};\n}\n`;
s=s.replace(anchor,insert+anchor);

const old=`    }catch(workerErr){\n      try{\n        const traktUrl=type==='movie'?'https://trakt.tv/users/snoak/lists/trakt-s-trending-movies':'https://trakt.tv/users/snoak/lists/trakt-s-trending-shows';\n        curated[key]=await fetchPublicTraktTrending(traktUrl,type);\n        console.log(\`Seed Snoak \${key}: \${curated[key].items.length} direct Trakt fallback entries.\`);\n      }catch(traktErr){\n        try{curated[key]=await fetchPublicMdbList(url,type);console.log(\`Seed Snoak \${key}: \${curated[key].items.length} MDBList public fallback entries.\`)}\n        catch(publicErr){console.warn(\`Snoak \${key} seed refresh unavailable: \${workerErr.message}; Trakt fallback: \${traktErr.message}; MDBList fallback: \${publicErr.message}\`);if(previous?.curated?.[key]?.items?.length>=100)curated[key]=previous.curated[key]}\n      }\n    }\n`;
const next=`    }catch(workerErr){\n      try{\n        curated[key]=await fetchTraktMediaSurface(type);\n        console.log(\`Seed Snoak \${key}: \${curated[key].items.length} current Trakt media-surface entries.\`);\n      }catch(mediaErr){\n        try{\n          const traktUrl=type==='movie'?'https://trakt.tv/users/snoak/lists/trakt-s-trending-movies':'https://trakt.tv/users/snoak/lists/trakt-s-trending-shows';\n          curated[key]=await fetchPublicTraktTrending(traktUrl,type);\n          console.log(\`Seed Snoak \${key}: \${curated[key].items.length} direct Snoak Trakt fallback entries.\`);\n        }catch(traktErr){\n          try{curated[key]=await fetchPublicMdbList(url,type);console.log(\`Seed Snoak \${key}: \${curated[key].items.length} MDBList public fallback entries.\`)}\n          catch(publicErr){console.warn(\`Snoak \${key} seed refresh unavailable: \${workerErr.message}; Trakt media: \${mediaErr.message}; Snoak Trakt: \${traktErr.message}; MDBList: \${publicErr.message}\`);if(previous?.curated?.[key]?.items?.length>=100)curated[key]=previous.curated[key]}\n        }\n      }\n    }\n`;
if(!s.includes(old)) throw new Error('Curated fallback block anchor not found');
s=s.replace(old,next);
fs.writeFileSync(path,s);
try{fs.rmSync('.promotion/promote-pending.mjs')}catch{}
execFileSync('git',['config','user.name','github-actions[bot]']);
execFileSync('git',['config','user.email','41898282+github-actions[bot]@users.noreply.github.com']);
execFileSync('git',['add','-A'],{stdio:'inherit'});
execFileSync('git',['commit','-m','Use Trakt media surface for v0.8.41 seed fallback [skip ci]'],{stdio:'inherit'});
execFileSync('git',['push','origin','HEAD:main'],{stdio:'inherit'});
console.log('v0.8.41 Trakt media-surface seed fallback promoted.');
